public enum BuffValueModifyTarget_Type{ none,BuffValueModifyTarget_health,BuffValueModifyTarget_Defend,BuffValueModifyTarget_HealthUp,BuffValueModifyTarget_maxHealth,BuffValueModifyTarget_toolDamage,

}
